name: typecheck, run tests then publish
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Repo
      uses: actions/checkout@v3.3.0
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with: 
        node-version: 18
    - name: NPM Install
      run: npm ci
    - name: Run tests
      run: npm run test
    
    - name: Monitor coverage
      uses: slavcodev/coverage-monitor-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        coverage_path: "logs/coverage.xml"
    
    
     
