name: typecheck, run tests then publish
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  typecheck:
    runs-on: ubuntu-latest
    needs: install-dependencies

    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Repo
      uses: actions/checkout@v3.3.0
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with: 
        node-version: 18
    - name: NPM Install
      run: npm ci

    - name: Run typecheck
      run: npx tsc --noEmit

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Repo
      uses: actions/checkout@v3.3.0
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with: 
        node-version: 18
    - name: NPM Install
      run: npm ci

    - name: coverage test
      run: npx vitest --coverage
    - name: 'Report Coverage'
      if: always() # Also generate the report if tests are failing
      uses:  davelosert/vitest-coverage-report-action@v1
  
  publishnpm:
    needs: [typecheck, test]

    name: Publish Package to npmjs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3.3.0
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


