name: typecheck, run tests then publish
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Repo
      uses: actions/checkout@v3.3.0
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with: 
        node-version: 18
    - name: NPM Install
      run: npm ci
    - name: Run tests
      run: npm run test
    
    - name: Monitor coverage
      uses: devmasx/coverage-check-action@v1.2.0
      with:
        type: lcov
        result_path: coverage/example.lcov
        min_coverage: 90
        token: ${{ github.token }}



    
     
